# Setup
title:               Being a person
tagline:             'Sometimes'
description:         'Some ramblings of me'
# url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty
plugins:
  - jekyll-spaceship

# About/contact
author:
  name:              Marlon Blencowe
  # url:               
  email:             marlonblencowe@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-spaceship

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
